Pages/Cognito.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;

using Amazon.AspNetCore.Identity.Cognito;
using Amazon.DynamoDBv2;
using Amazon.Extensions.CognitoAuthentication;
using Amazon.Lambda.Core;

using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AwsAspCore.Pages
{
    public class CognitoModel : PageModel
    {
        private SignInManager<CognitoUser> signInManager;
        private CognitoUserManager<CognitoUser> userManager;
        private RoleManager<CognitoRole> roleManager;

        public CognitoModel(SignInManager<CognitoUser> signInManager, UserManager<CognitoUser> userManager, RoleManager<CognitoRole> roleManager)
        {
            this.signInManager = signInManager;
            this.userManager = userManager as CognitoUserManager<CognitoUser>;
            this.roleManager = roleManager;
        }

        public string Message { get; set; }

        public bool SignedIn { get; set; }

        public CognitoUser CUser { get; set; }

        public async Task OnGetAsync(string message = null)
        {
            Message = HttpUtility.UrlDecode(message);
            SignedIn = signInManager.IsSignedIn(User);
            CUser = await userManager.GetUserAsync(User);
        }

        public async Task<IActionResult> OnPostLoginAsync(string username, string password, bool rememberMe = false)
        {
            var result = await signInManager.PasswordSignInAsync(username, password, rememberMe, false);
            if (result.Succeeded)
            {
                return RedirectToPage("/Cognito", new { message = "Login Success!" });
            }
            else
            {
                return RedirectToPage("/Cognito", new { message = "Login Failed!" });
            }
        }

        public async Task<IActionResult> OnPostLogoutAsync()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToPage("/Cognito", new { message = "You are already logged out" });
            }

            await signInManager.SignOutAsync();
            return RedirectToPage("/Cognito", new { message = "Logged Out!" });
        }

        public async Task<IActionResult> OnPostToggleRedRoleAsync()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToPage("/Cognito", new { message = "You need to be logged in to toggle your red role" });
            }

            var user = await userManager.GetUserAsync(User);
            if (await userManager.IsInRoleAsync(user, "red"))
            {
                await userManager.RemoveFromRoleAsync(user, "red");
                return RedirectToPage("/Cognito", new { message = "No longer in the red role. You will no longer be able to play the red game when you next log in." });
            }
            else
            {
                await userManager.AddToRoleAsync(user, "red");
                return RedirectToPage("/Cognito", new { message = "Your now in the red role! Relog to play the red game." });
            }
        }
    }
}

Pages/ContentMod.cshtml.cs
using System;
using System.IO;
using System.Threading.Tasks;

using Amazon.Lambda.Core;
using Amazon.Rekognition;
using Amazon.Rekognition.Model;

using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AwsAspCore.Pages
{
    public class ContentModModel : PageModel
    {
        private IAmazonRekognition rekognition;

        public ContentModModel(IAmazonRekognition rekognition)
        {
            this.rekognition = rekognition;
        }

        [BindProperty]
        public IFormFile Upload { get; set; }

        public DetectModerationLabelsResponse Result { get; set; }

        public async Task OnPostAsync()
        {
            using (var fileStream = Upload.OpenReadStream())
            {
                using (var ms = new MemoryStream())
                {
                    fileStream.CopyTo(ms);

                    Result = await rekognition.DetectModerationLabelsAsync(new DetectModerationLabelsRequest
                    {
                        Image = new Image
                        {
                            Bytes = ms,
                        }
                    });
                }
            }
        }
    }
}

Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AwsAspCore.Pages
{
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/Game.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AwsAspCore.Pages
{
    public class GameModel : PageModel
    {
        public string Color { get; set; }

        public IActionResult OnGet(string color)
        {
            if (color == "red")
            {
                if (!User.Identity.IsAuthenticated)
                {
                    return RedirectToPage("/Cognito", new { message = "You need to be logged in to play the red game" });
                }

                if (!User.IsInRole("red"))
                {
                    return RedirectToPage("/Cognito", new { message = "You need to have the red group to play the red game" });
                }
            }

            Color = color ?? "none";

            return Page();
        }
    }
}

Pages/Help.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AwsAspCore.Pages
{
    public class HelpModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {

        }
    }
}

Pages/Index.cshtml.cs
using System;
using System.Threading.Tasks;

using Amazon.DynamoDBv2;

using AwsAspCore.DDB;

using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AwsAspCore.Pages
{
    public class IndexModel : PageModel
    {
        IAmazonDynamoDB ddb;

        public IndexModel(IAmazonDynamoDB ddb)
        {
            this.ddb = ddb;
        }

        public int MovieCount { get; set; }

        public string Message { get; set; }

        public string SessionId { get; set; }

        public async Task OnGetAsync(string message)
        {
            SessionId = HttpContext.Session.GetString("session-guid");
            if (SessionId == null)
            {
                SessionId = Guid.NewGuid().ToString();
                HttpContext.Session.SetString("session-guid", SessionId);
            }

            Message = message ?? "";
            MovieCount = await ddb.Movies_Count();
        }

        //public async Task OnGetHelloWorldAsync()
        //{
        //    Message = "Hello World";
        //    MovieCount = await ddb.Movies_Count();
        //}
    }
}

Pages/Cognito.cshtml
@page
@model AwsAspCore.Pages.CognitoModel

<br />
<br />

@Model.Message

<br />
<br />

@if (Model.SignedIn)
{
    <text>
        Welcome @Model.CUser.Username
    </text>
    <br />
    <br />
    <form method="post">
        <input type="submit" value="Toggle Red Role" asp-page-handler="ToggleRedRole" />
    </form>
    <br />
    <br />
    <form method="post">
        <input type="submit" value="Logout" asp-page-handler="Logout" />
    </form>
}
else
{
    <form method="post">
        <label for="username">Username</label>
        <input type="text" id="username" name="username" />
        <label for="password">Password</label>
        <input type="password" id="password" name="password" />
        <label for="rememberMe">rememberMe</label>
        <input type="checkbox" id="rememberMe" name="rememberMe" />
        <input type="submit" value="Login" asp-page-handler="Login" />
    </form>

    <br />

    <a href="https://auth.awsaspcore.codari.co/signup?response_type=token&client_id=1l0770l149iano9rs8hu1lqh5c&redirect_uri=https://awsaspcore.codari.co/Cognito">Sign Up</a>
}

Pages/ContentMod.cshtml
@page
@model AwsAspCore.Pages.ContentModModel

<h2>Content Moderation</h2>

<form method="post" enctype="multipart/form-data">
    <input type="file" asp-for="Upload" />
    <input type="submit" />
</form>

<div>
    <h4>Results</h4>
    <hr />
    <dl class="dl-horizontal">

        @if (Model.Result != null)
        {
            @foreach (var label in Model.Result.ModerationLabels)
            {
                <hr />
                <div>
                    @label.Name : @label.ParentName
                    @label.Confidence %
                </div>
            }
        }
    </dl>
</div>

Pages/Game.cshtml
@page

@model AwsAspCore.Pages.GameModel

@*<iframe id="iframe"
        frameborder="0"
        src="@Url.Content($"https://soren025.github.io/webgl-game/?color={Model.Color}")"
        allowfullscreen=true
        webkitallowfullscreen=true
        mozallowfullscreen=true
        style="width: 100%;
        height: 700px;" />*@

<iframe id="iframe"
        frameborder="0"
        src="@Url.Content($"https://d3i1ren86jvbz2.cloudfront.net/?color={Model.Color}")"
        allowfullscreen=true
        webkitallowfullscreen=true
        mozallowfullscreen=true
        style="width: 100%;
        height: 700px;" />

Pages/Help.cshtml
@page
@model HelpModel
@{
    ViewData["Title"] = "Help";
}
<h2>Places to Find Additional Help.</h2>

<p></p>
<ul>
    <li><a href="https://github.com/aws/aws-lambda-dotnet">AWS Lambda .NET Core GitHub Repository</a></li>
    <li><a href="https://github.com/aws/aws-sdk-net">AWS SDK for .NET GitHub Repository</a></li>
    <li><a href="https://aws.amazon.com/blogs/developer/category/net/">AWS .NET Developer Blog</a></li>
    <li><a href="https://twitter.com/awsfornet">AWS .NET Twitter Handle</a></li>
    <li><a href="https://aws.amazon.com/documentation/sdk-for-net/">AWS .NET Developer Guide</a></li>
</ul>

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<h2>Congratulations!!! Your ASP.NET Core Web Application is now Serverless</h2>
<h3>There are @Model.MovieCount Movies</h3>
<h4>Session Id: @Model.SessionId</h4>
@if (Model.Message.Length > 0)
{
    <h4>Message: @Model.Message</h4>
}

<svg style="width:100%;height:800px;">
    <path class="path" fill="none" stroke="orange" stroke-width="2" stroke-miterlimit="10" d="M989,595H712v-35c0,0,4.5-1.8,8-3
                                                                                                  c5.2-1.8,12.5,5.3,22-4c3.4-3.4-0.9-7.8-0.4-10.1c0.7-3.1,4.4-6.8,1.6-11.4c-2.6-4.2-6.9-3.6-8.2-5.5c-1.7-2.3-2.2-6.3-7-9
                                                                                                  c-5.6-3.1-9.9,0.2-13-1c-2.5-0.9-2.3-5-9-5c-4.8,0-7.2,4.8-10,5c-2.3,0.2-4.9-4.5-10-2c-5.5,2.8-4,7.3-6,9c-1.4,1.2-3.1,3.2-6,4.2
                                                                                                  c-2.6,0.9-4.9,3-4,8.8c0.6,3.7,6.8,4.1,7.5,6c1,2.9-6.4,6.2-2.5,12c3,4.5,9,1.6,12,1c1.9-0.4,7.1-0.7,8,0c3.4,2.5,9,5,9,5v35
                                                                                                  l-506-1.5L182.3,444l0.3-0.8v-69.6l-0.2-0.2l12.3-72.3c10.9-2.6,16.5-6.5,16.5-6.5l-5.2-2.9l1.1-5.8l15-3.3l-10.1-3.9l1.2-4.6
                                                                                                  c-15.8-8.3-32.2-11-32.2-11v-3.6l4.1-6.5h-4.9v-4.4h-8.3V244h-1.2l-1.7-31.2l-1-1.3l-1,1.3l-1.7,31.2h-1.2v4.8h-8.3v4.4h-4.9
                                                                                                  l4.1,6.5v3.6c0,0-16.5,2.7-32.2,11l1.2,4.6l-10.1,3.9l15,3.3l1.1,5.8l-5.1,2.9c0,0,5.5,3.9,16.4,6.5l12.3,72.4l-0.1,0.1v69.6
                                                                                                  l0.3,0.8l-14.6,149.4h-1.2H-11" />

    <path class="path" fill="none" stroke="orange" stroke-width="2" stroke-miterlimit="10" d="M8,393.7c0-13.5,12.1-10.8,15.6-14.7
                                                                                                  c2.8-3.2-1-8.8,9-13.9c7.9-4.1,9.7,1,13.1,0.8c4.5-0.3,3.3-6.7,14.7-6.6c12.7,0.2,11.2,8.4,14.7,10.6c3,1.9,7.9-2.1,13.9,4.1
                                                                                                  c3.8,4,1.3,7.4,2.5,9.8c2.2,4.4,14.7,0.9,14.7,13.9c0,12.2-13.5,8.3-17.2,10.6c-3.6,2.3-4.4,9.3-13.1,11.5c-8,2-9.5-4-13.9-4.1
                                                                                                  c-5-0.1-5.5,8.6-18.8,6.6c-12.3-1.9-12.3-9.1-16.4-12.3C21.9,406.3,8,408.6,8,393.7z" />


    <path class="path" fill="none" stroke="orange" stroke-width="2" stroke-miterlimit="10" d="M325.1,313.9c-3.9,3-3.9,10-15.7,11.8
                                                                                                  c-12.8,2-13.3-6.4-18-6.3c-4.3,0.1-5.7,5.8-13.3,3.9c-8.4-2.1-9.1-8.8-12.5-11c-3.6-2.3-16.5,1.5-16.5-10.2c0-12.4,12-9.1,14.1-13.3
                                                                                                  c1.1-2.3-1.3-5.6,2.4-9.4c5.8-6,10.4-2.1,13.3-3.9c3.4-2.1,2-10,14.1-10.2c11-0.2,9.9,6,14.1,6.3c3.3,0.2,5-4.7,12.5-0.8
                                                                                                  c9.6,4.9,6,10.3,8.6,13.3c3.3,3.7,14.9,1.2,14.9,14.1C343.1,312.5,329.8,310.3,325.1,313.9z" />

    <path class="path" fill="none" stroke="orange" stroke-width="2" stroke-miterlimit="10" d="M18.4,229.5c0-13.5,12.1-10.8,15.6-14.7
                                                                                                  c2.8-3.2-1-8.8,9-13.9c7.9-4.1,9.7,1,13.1,0.8c4.5-0.3,3.3-6.7,14.7-6.6c12.7,0.2,11.2,8.4,14.7,10.6c3,1.9,7.9-2.1,13.9,4.1
                                                                                                  c3.8,4,1.3,7.4,2.5,9.8c2.2,4.4,14.7,0.9,14.7,13.9c0,12.2-13.5,8.3-17.2,10.6c-3.6,2.3-4.4,9.3-13.1,11.5c-8,2-9.5-4-13.9-4.1
                                                                                                  c-5-0.1-5.5,8.6-18.8,6.6c-12.3-1.9-12.3-9.1-16.4-12.3C32.2,242.1,18.4,244.4,18.4,229.5z" />

    <path class="path" fill="none" stroke="orange" stroke-width="2" stroke-miterlimit="10" d="M215.8,398.8c0-13.5,12.1-10.8,15.6-14.7
                                                                                                  c2.8-3.2-1-8.8,9-13.9c7.9-4.1,9.7,1,13.1,0.8c4.5-0.3,3.3-6.7,14.7-6.6c12.7,0.2,11.2,8.4,14.7,10.6c3,1.9,7.9-2.1,13.9,4.1
                                                                                                  c3.8,4,1.3,7.4,2.5,9.8c2.2,4.4,14.7,0.9,14.7,13.9c0,12.2-13.5,8.3-17.2,10.6c-3.6,2.3-4.4,9.3-13.1,11.5c-8,2-9.5-4-13.9-4.1
                                                                                                  c-5-0.1-5.5,8.6-18.8,6.6c-12.3-1.9-12.3-9.1-16.4-12.3C229.7,411.3,215.8,413.6,215.8,398.8z" />

</svg>

Pages/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AwsAspCore</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-page="/Index" class="navbar-brand">AwsAspCore</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-page="/Index">Home</a></li>
                    <li><a href="@Url.Page("/Index", new { message = "Hello World" })">Home With Message</a></li>
                    <li><a asp-page="/Help">Help</a></li>
                    <li><a href="@Url.Page("/Movies/Index", new { sortBy = "title" })">Movies</a></li>
                    <li><a href="@Url.Page("/Game")">Game</a></li>
                    @if (User.Identity.IsAuthenticated && User.IsInRole("red"))
                    {
                        <li><a href="@Url.Page("/Game", new { color = "red" })">Game Red</a></li>
                    }
                    @*<li><a href="@Url.Page("/Game", new { color = "blue" })">Game Blue</a></li>
                    <li><a href="@Url.Page("/Game", new { color = "green" })">Game Green</a></li>*@
                    <li><a asp-page="/Images/Index">Images</a></li>
                    <li><a asp-page="/ContentMod">Content Moderation</a></li>
                    <li><a asp-page="/Cognito">Cognito</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2020 - Codari</p>
            <p><a href="https://github.com/Soren025/AwsAspCore">Project Github</a></p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>